---
# This is necessary to install the latest versions of Postgres
# For details see https://wiki.postgresql.org/wiki/Apt

- name: Add R repo to sources list
  apt_repository: repo='ppa:marutter/rrutter' state=present
  sudo: yes

