---
- include: add-apt-repo-for-r.yml

- name: install R packages 
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  tags: [packages]
  with_items:
    - libpq-dev
    - r-base
    - r-base-dev