---
- name: Install | Download Scala
  get_url: dest=/var/local/ansible-cache/ url=http://www.scala-lang.org/files/archive/scala-{{scala_version}}.tgz
  sudo: yes
  tags: [scala]

- name: Install | Extract Scala
  shell: tar xzf /var/local/ansible-cache/scala-{{scala_version}}.tgz -C {{software_install_dir}} creates=/usr/local/share/scala-{{scala_version}}
  sudo: yes
  tags: [scala]

- name: Configure | Add Scala executable symlinks to path
  shell: for f in fsc scala scalac scaladoc scalap; do ln -s {{software_install_dir}}/scala-{{scala_version}}/bin/$f /usr/local/bin/$f; done; creates={{software_install_dir}}/scala
  sudo: yes
  tags: [scala]

- name: Configure | Update Scala environment variables
  sudo: no
  lineinfile: line="export SCALA_HOME={{software_install_dir}}/scala" dest="~/.bashrc" state=present regexp="export SCALA_HOME={{software_install_dir}}/scala"
  tags: [scala]
