---
- name: install zsh packages
  sudo: yes
  apt: pkg={{ item }} state=installed
  tags: [packages]
  with_items:
    - zsh
    - zsh-doc

- name: Pipe oh-my-zsh installation script into zsh
  sudo: yes
  shell: wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh creates=/home/vagrant/.oh-my-zsh

- name: 'You now need to change shells by executing "chsh -s `which zsh`" at the command line, entering the vagrant password and then exiting / starting a new shell session'
  shell: chsh -s `which zsh`

# - name: Change shell
#   shell: chsh -s `which zsh`

# Print a helpful message
# - name: You will need to exit the terminal and then start a new terminal session before oh-my-zsh is live
#   command: echo "You will need to exit the terminal and then start a new terminal session before oh-my-zsh is live"