---
- name: Install PyCurl (required for apt-repository updates)
  apt: pkg=python-pycurl
  tags:
    - packages
    - java

- name: Install Oracle Java Repo Installer Repository
  apt_repository: repo=ppa:webupd8team/java update-cache=yes
  tags: [java]

- name: Wizardry to bypass the Oracle License File prompt
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
  tags: [java]

- name: Install Oracle Java 7
  apt: pkg=oracle-java7-installer
  tags: [java]