---

# curl required to download RVM     
- name: Ensure curl is installed (used to download RVM)
  apt: pkg={{ item }} state=installed
  tags: [packages]
  sudo: yes
  with_items:
    - curl       

# INSTALL RVM
- name: Ensure RVM is installed
  shell: curl -L https://get.rvm.io | bash -s stable --ruby creates=/home/vagrant/.rvm

# INSTALL Ruby 1.9.3
- name: Ensure Ruby 1.9.3 is installed as default
  shell: '/home/vagrant/.rvm/bin/rvm install --default {{ default_ruby_version }} creates=/usr/local/rvm/rubies/{{ default_ruby_version }}'
  tags: [ruby]

# Launch RVM. Note that when testing, this doesn't have the desired effect. 
# (I.e. user still needs to exit the shell and re-enter before RVM is available.) 
# Hence the warning in the next stepru
- name: Launch RVM (otherwise only launched when the shell is rebooted)
  shell: 'executable=/home/vagrant/.rvm/scripts/rvm && rvm use --default {{ default_ruby_version }} && bundle'


# Print a useful warning
- name: NOTICE! You will need to exit the terminal and open a fresh terminal before you can use RVM. \n(Or alternatively run '. /home/vagrant/.rvm/scripts/rvm
  shell: echo "You will need to exit the terminal and open a fresh terminal before you can use RVM. \n(Or alternatively run '. /home/vagrant/.rvm/scripts/rvm'"
